# Generated by Django 2.1.4 on 2022-10-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('giacenza', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Articoli',
                'verbose_name': 'Articolo',
            },
        ),
    ]
